name: Update File
on:
  schedule:
    - cron: "*/35 * * * *"
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          echo $(date '+%Y-%m-%d %H:%M:%S') > Update

      - name: Commit and push changes
        run: |
          git config --global user.name "TristanLanvins"
          git config --global user.email "TristanLanvins@github.com"
          git add Update
          git commit -m "Update Path of Exile Trade Bot"
          git push
